version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_bot_db_prod
    environment:
      POSTGRES_DB: todo_bot
      POSTGRES_USER: todo_bot_user
      POSTGRES_PASSWORD: ${DB_PASSWORD} # Будет браться из .env
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_bot_user -d todo_bot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - todo_network

  bot:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: todo_bot_prod
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo_network

volumes:
  postgres_data:

networks:
  todo_network:
    driver: bridge