version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: todo_bot_db
    environment:
      POSTGRES_DB: todo_bot
      POSTGRES_USER: todo_bot_user
      POSTGRES_PASSWORD: your_secure_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U todo_bot_user -d todo_bot"]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: todo_bot
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=todo_bot
      - DB_USER=todo_bot_user
      - DB_PASSWORD=your_secure_password_here
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: